#!/usr/bin/env bash
# check-doc-gate-test.sh — fixture tests for scripts/check-doc-gate.sh, run
# against throwaway git repos so real commits/diffs exercise the checker
# instead of mocking git. Covers both trivial paths in trivial_change():
# the pre-existing "// doc-gate:trivial" marker on a single declaration, and
# the marker-free provenance-row exemption for generated struct-literal table
# rows (go-kure/.github#216).
#
# Usage: check-doc-gate-test.sh [REPO_ROOT]

set -uo pipefail  # not -e: report every assertion, not just the first failure

ROOT="${1:-.}"
ROOT="$(cd "$ROOT" && pwd)"
CHECKER="$ROOT/scripts/check-doc-gate.sh"

failures=0
pass_count=0

assert_rc() {
  local desc="$1" expected="$2" actual="$3"
  if [ "$expected" = "$actual" ]; then
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $desc — expected rc=$expected, got rc=$actual" >&2
    failures=$((failures + 1))
  fi
}

new_repo() {
  local dir
  dir="$(mktemp -d)"
  git -C "$dir" init -q -b main
  git -C "$dir" config user.email "test@example.invalid"
  git -C "$dir" config user.name "Test"
  echo "$dir"
}

# Portable in-place edit. GNU sed accepts a bare `-i`; BSD/macOS sed requires
# the backup suffix immediately after it and would otherwise consume the
# script as that suffix — the whole suite would error out instead of
# asserting anything, on the one environment whose `wc -l` padding
# check-doc-gate.sh explicitly accommodates (go-kure/.github#218 review,
# round 6). Rewriting through a sibling temp file behaves identically
# everywhere. Expressions stay BRE (no -E): `{` and `}` are literal there,
# which several fixtures below rely on.
subst() {
  local expr="$1" file="$2"
  sed "$expr" "$file" > "$file.tmp" && mv "$file.tmp" "$file"
}

docs_map() {
  cat <<'EOF'
repo_type: go-library
docs_only: false
code_roots: [pkg]
packages:
  - path: pkg/tables
    readme: pkg/tables/README.md
    guides: []
EOF
}

# Base fixture shared by every case below: one doc-mapped package whose only
# source file is a generated table with two rows, plus its README.
base_fixture() {
  local dir="$1"
  mkdir -p "$dir/pkg/tables"
  docs_map > "$dir/docs-map.yaml"
  cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true},
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Alertmanager", ModuleVersion: "v0.93.1", Namespaced: true},
}
EOF
  echo "# tables" > "$dir/pkg/tables/README.md"
  git -C "$dir" add -A && git -C "$dir" commit -q -m base
  git -C "$dir" branch -q base_marker
}

run_gate() {
  local dir="$1"
  (cd "$dir" && bash "$CHECKER" base_marker .) >/dev/null 2>&1
}

# --- Provenance-row path (new, go-kure/.github#216) --------------------

# Fixture 1: both rows' ModuleVersion bumped, nothing else changed, no README
# touch -> OK. This is the go-kure/kure#793 / go-kure/kure#806 shape.
dir="$(new_repo)"; base_fixture "$dir"
subst 's/v0\.93\.1/v0.94.0/g' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump ModuleVersion"
run_gate "$dir"
assert_rc "provenance-only row bump, no doc touch -> OK" "0" "$?"
rm -rf "$dir"

# Fixture 2: the same bump again, as a plain repeat -> OK. Isolation check:
# confirms fixture 1's result isn't an artifact of some one-shot state left
# over in the checker (e.g. a cache or a global that only behaves on a
# fixture's first run).
dir="$(new_repo)"; base_fixture "$dir"
subst 's/v0\.93\.1/v0.94.0/g' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump ModuleVersion only"
run_gate "$dir"
assert_rc "provenance-only row bump (repeat, isolation check) -> OK" "0" "$?"
rm -rf "$dir"

# Fixture 3: Kind renamed alongside the SAME ModuleVersion bump, no README
# touch -> FAIL. A row identity change is never provenance-only, even when a
# provenance field also changed on the same line.
dir="$(new_repo)"; base_fixture "$dir"
subst 's/Kind: "Prometheus"/Kind: "PrometheusAgent"/; s/v0\.93\.1/v0.94.0/g' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "rename kind + bump version"
run_gate "$dir"
assert_rc "kind renamed alongside version bump -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 4: Namespaced flipped, ModuleVersion unchanged -> FAIL. A scope
# change is a real documentation decision (pkg/kubernetes/README.md's own
# stated rule), not provenance churn.
dir="$(new_repo)"; base_fixture "$dir"
# Address the Prometheus row by name rather than with a `0,/re/` range: that
# line-0 form is a GNU extension and is a syntax error in BSD sed.
subst '/Kind: "Prometheus"/s/Namespaced: true/Namespaced: false/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "flip Namespaced"
run_gate "$dir"
assert_rc "scope change with no version bump -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 5: a row added (line count changes) -> FAIL. The hunk-size guard
# (newcount == oldcount) must still block this; the provenance path never
# even gets a chance to run on an unbalanced hunk.
dir="$(new_repo)"; base_fixture "$dir"
# Rewrite the whole file rather than appending with `/re/a\text`: the
# one-line form of the append command is a GNU extension, and portable sed
# needs the text on its own continuation line.
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true},
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Alertmanager", ModuleVersion: "v0.93.1", Namespaced: true},
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "PodMonitor", ModuleVersion: "v0.93.1", Namespaced: true},
}
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add a row"
run_gate "$dir"
assert_rc "row added, no doc touch -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 6: the identical ModuleVersion-only edit, but the file carries no
# "Code generated ... DO NOT EDIT." header -> FAIL. is_generated_file() must
# still gate the provenance path exactly as it gates the marker path; a
# hand-written file cannot self-exempt by merely looking like a table.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// hand-written, not generated

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true},
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Alertmanager", ModuleVersion: "v0.93.1", Namespaced: true},
}
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/v0\.93\.1/v0.94.0/g' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump version, no header"
run_gate "$dir"
assert_rc "version bump without generated-code header -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7: a pathological line carrying the recognized field name twice,
# with only the FIRST occurrence's value changing -> FAIL.
# mask_provenance_field()'s exactly-one-occurrence guard must reject this
# rather than mask just the first match: masking only the first occurrence
# would make the two lines byte-identical (the untouched second occurrence
# matches on both sides too), so a broken occurrence count that never
# rejects a multi-match line would falsely accept this as trivial even
# though nothing proves the SECOND occurrence didn't also carry a real
# change hidden behind the mask.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// pathological: two ModuleVersion occurrences on one line
var _ = struct{ A, B string }{ModuleVersion: "v0.93.1", ModuleVersion: "v0.93.1"}
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add pathological line"
git -C "$dir" branch -qf base_marker HEAD
# Target only the pathological line (an unaddressed s/// replaces the first
# occurrence on EVERY line, including the base rows above) and let the lack
# of /g replace only its first occurrence on that line.
subst '/struct{ A, B string }/s/v0\.93\.1/v0.94.0/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump only the first occurrence"
run_gate "$dir"
assert_rc "field name appears twice, only first occurrence changes -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7b: a longer field NAME that merely ends in the recognized field
# name (e.g. a hypothetical "MinimumModuleVersion") must not be matched as
# if it were "ModuleVersion" -> FAIL. An unanchored `${field}: "..."` regex
# matches this as a substring; the struct-literal anchor (must be
# immediately preceded by `{` or `,`) rules it out.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
var _ = struct{ MinimumModuleVersion string }{MinimumModuleVersion: "v0.93.1"}
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add MinimumModuleVersion line"
git -C "$dir" branch -qf base_marker HEAD
subst 's/MinimumModuleVersion: "v0\.93\.1"/MinimumModuleVersion: "v0.94.0"/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump the longer field name"
run_gate "$dir"
assert_rc "field name that merely ends in ModuleVersion -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7c: a comment line whose PROSE happens to contain
# "ModuleVersion: \"...\"" (not a struct-literal field) -> FAIL. The
# unanchored regex would match this as if it were a real row; the
# struct-literal anchor requires immediate precedence by `{`/`,`, which a
# comment's "...: " never provides.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Compatibility: ModuleVersion: "legacy"
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add comment line"
git -C "$dir" branch -qf base_marker HEAD
subst 's/ModuleVersion: "legacy"/ModuleVersion: "current"/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "edit the comment prose"
run_gate "$dir"
assert_rc "comment prose matching the field pattern -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7d: a comment line whose example text happens to satisfy the
# struct-literal anchor too (`{ModuleVersion: "..."}` appearing right after
# `//`) -> FAIL. The `{`/`,` anchor alone doesn't prove real Go syntax --
# those characters can appear inside a comment's own prose. code_part()
# strips everything from the line's first `//`/`/*` before matching, so a
# full-line comment's code part is empty and never matches.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Example: {ModuleVersion: "v0.93.1"}
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add example comment"
git -C "$dir" branch -qf base_marker HEAD
subst 's/{ModuleVersion: "v0\.93\.1"}/{ModuleVersion: "v0.94.0"}/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "edit the example comment"
run_gate "$dir"
assert_rc "comment example satisfying the struct-literal anchor -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7e: the same trap, but as a comment trailing real code on the
# SAME line rather than a full line to itself -> FAIL. A line that merely
# starts with non-comment code but ends in a matching comment doesn't
# start with `//`, so an earlier full-line-only check would miss it;
# code_part() strips from the first `//` regardless of what precedes it.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
var sentinel = 1 // Example: {ModuleVersion: "v0.93.1"}
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add trailing-comment line"
git -C "$dir" branch -qf base_marker HEAD
subst 's/{ModuleVersion: "v0\.93\.1"}/{ModuleVersion: "v0.94.0"}/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "edit the trailing comment"
run_gate "$dir"
assert_rc "comment trailing real code on the same line -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7f: a real row whose ModuleVersion bumps AND whose OWN trailing
# comment changes in the same commit -> FAIL. code_part() drops the comment
# only for MATCHING; mask_provenance_field() re-attaches it verbatim to the
# returned value, so a changed comment still fails the equality check the
# same as any other unrelated change on the line.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true}, // stable
}
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/v0\.93\.1/v0.94.0/; s#// stable#// under review#' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump version and edit trailing comment"
run_gate "$dir"
assert_rc "version bump AND its own trailing comment change -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7g: the same row, comment UNCHANGED, only ModuleVersion bumps ->
# OK. Isolation check for 7f: a real row merely HAVING a trailing comment
# must not itself defeat the exemption.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true}, // stable
}
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/v0\.93\.1/v0.94.0/' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump version, comment untouched"
run_gate "$dir"
assert_rc "version bump, trailing comment unchanged -> OK" "0" "$?"
rm -rf "$dir"

# --- Regression: pre-existing marker path must still work unchanged -----

# Fixture 8: marker-path package mapped — const bump WITH marker -> OK.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
cat > "$dir/docs-map.yaml" <<'EOF'
repo_type: go-library
docs_only: false
code_roots: [pkg]
packages:
  - path: pkg/tables
    readme: pkg/tables/README.md
    guides: []
EOF
cat > "$dir/pkg/tables/gen.go" <<'EOF'
// Code generated by sync-versions.sh; DO NOT EDIT.

package tables

const GoVersion = "1.25.0" // doc-gate:trivial
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/1\.25\.0/1.26.0/' "$dir/pkg/tables/gen.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump go version"
run_gate "$dir"
assert_rc "marked const value bump, no doc touch -> OK (regression)" "0" "$?"
rm -rf "$dir"

# Fixture 9: same file, value bumped WITHOUT the marker -> FAIL (regression).
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
cat > "$dir/docs-map.yaml" <<'EOF'
repo_type: go-library
docs_only: false
code_roots: [pkg]
packages:
  - path: pkg/tables
    readme: pkg/tables/README.md
    guides: []
EOF
cat > "$dir/pkg/tables/gen.go" <<'EOF'
// Code generated by sync-versions.sh; DO NOT EDIT.

package tables

const GoVersion = "1.25.0"
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/1\.25\.0/1.26.0/' "$dir/pkg/tables/gen.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump go version, no marker"
run_gate "$dir"
assert_rc "unmarked const value bump, no doc touch -> FAIL (regression)" "1" "$?"
rm -rf "$dir"

# --- The two recognizers must be independent, not exclusive ------------

# Fixture 10: a generated struct-literal row that ALSO carries the
# `// doc-gate:trivial` marker, bumped provenance-only -> OK. The marker
# path's `${line%%=*}` word-compare cannot accept a row with no top-level
# `=` (it compares the whole line, and the version token differs), so if a
# failed marker compare aborts the whole file instead of falling through,
# adding the marker makes a row STRICTER than the identical unmarked row in
# fixture 1 -- the marker would be a trap rather than a hint, and the
# "second, independent test" the checker's own header claims would in fact
# be exclusive (go-kure/.github#218 review, round 7).
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true}, // doc-gate:trivial
}
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/v0\.93\.1/v0.94.0/' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump version on a marked row"
run_gate "$dir"
assert_rc "marked struct row, provenance-only bump -> OK" "0" "$?"
rm -rf "$dir"

# Fixture 11: the same marked row, but with Kind renamed as well -> FAIL.
# Isolation check for fixture 10: falling through from a failed marker
# compare must reach the provenance recognizer's STRICT rule, not bypass
# it. A marked row must be no more permissive than an unmarked one.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true}, // doc-gate:trivial
}
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/Kind: "Prometheus"/Kind: "PrometheusAgent"/; s/v0\.93\.1/v0.94.0/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "rename kind on a marked row"
run_gate "$dir"
assert_rc "marked struct row, kind renamed too -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 12: a MARKED const whose identifier changes -> FAIL. This is the
# exact case the removed `|| return 1` used to reject outright, so it is the
# axis the round-7 fallthrough could regress: after falling through, the
# line must still be rejected by the provenance recognizer (a const carries
# no PROVENANCE_FIELDS field, so nothing can mask it equal).
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/gen.go" <<'EOF'
// Code generated by sync-versions.sh; DO NOT EDIT.

package tables

const GoVersion = "1.25.0" // doc-gate:trivial
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
subst 's/const GoVersion = "1\.25\.0"/const GoLangVersion = "1.26.0"/' \
  "$dir/pkg/tables/gen.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "rename a marked const"
run_gate "$dir"
assert_rc "marked const whose identifier changes -> FAIL" "1" "$?"
rm -rf "$dir"

echo "passed: $pass_count, failed: $failures"
[ "$failures" -eq 0 ]
