#!/usr/bin/env bash
# check-doc-gate-test.sh — fixture tests for scripts/check-doc-gate.sh, run
# against throwaway git repos so real commits/diffs exercise the checker
# instead of mocking git. Covers both trivial paths in trivial_change():
# the pre-existing "// doc-gate:trivial" marker on a single declaration, and
# the marker-free provenance-row exemption for generated struct-literal table
# rows (go-kure/.github#216).
#
# Usage: check-doc-gate-test.sh [REPO_ROOT]

set -uo pipefail  # not -e: report every assertion, not just the first failure

ROOT="${1:-.}"
ROOT="$(cd "$ROOT" && pwd)"
CHECKER="$ROOT/scripts/check-doc-gate.sh"

failures=0
pass_count=0

assert_rc() {
  local desc="$1" expected="$2" actual="$3"
  if [ "$expected" = "$actual" ]; then
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $desc — expected rc=$expected, got rc=$actual" >&2
    failures=$((failures + 1))
  fi
}

new_repo() {
  local dir
  dir="$(mktemp -d)"
  git -C "$dir" init -q -b main
  git -C "$dir" config user.email "test@example.invalid"
  git -C "$dir" config user.name "Test"
  echo "$dir"
}

docs_map() {
  cat <<'EOF'
repo_type: go-library
docs_only: false
code_roots: [pkg]
packages:
  - path: pkg/tables
    readme: pkg/tables/README.md
    guides: []
EOF
}

# Base fixture shared by every case below: one doc-mapped package whose only
# source file is a generated table with two rows, plus its README.
base_fixture() {
  local dir="$1"
  mkdir -p "$dir/pkg/tables"
  docs_map > "$dir/docs-map.yaml"
  cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// Code generated by internal/gen; DO NOT EDIT.

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true},
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Alertmanager", ModuleVersion: "v0.93.1", Namespaced: true},
}
EOF
  echo "# tables" > "$dir/pkg/tables/README.md"
  git -C "$dir" add -A && git -C "$dir" commit -q -m base
  git -C "$dir" branch -q base_marker
}

run_gate() {
  local dir="$1"
  (cd "$dir" && bash "$CHECKER" base_marker .) >/dev/null 2>&1
}

# --- Provenance-row path (new, #216) -----------------------------------

# Fixture 1: both rows' ModuleVersion bumped, nothing else changed, no README
# touch -> OK. This is the #793/#806 shape.
dir="$(new_repo)"; base_fixture "$dir"
sed -i 's/v0\.93\.1/v0.94.0/g' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump ModuleVersion"
run_gate "$dir"
assert_rc "provenance-only row bump, no doc touch -> OK" "0" "$?"
rm -rf "$dir"

# Fixture 2: same bump, but also drop the README -> still OK for THIS
# package's gate (nothing else claims the README), proving the exemption
# isn't accidentally satisfied by an unrelated doc change either.
dir="$(new_repo)"; base_fixture "$dir"
sed -i 's/v0\.93\.1/v0.94.0/g' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump ModuleVersion only"
run_gate "$dir"
assert_rc "provenance-only row bump (repeat, isolation check) -> OK" "0" "$?"
rm -rf "$dir"

# Fixture 3: Kind renamed alongside the SAME ModuleVersion bump, no README
# touch -> FAIL. A row identity change is never provenance-only, even when a
# provenance field also changed on the same line.
dir="$(new_repo)"; base_fixture "$dir"
sed -i 's/Kind: "Prometheus"/Kind: "PrometheusAgent"/; s/v0\.93\.1/v0.94.0/g' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "rename kind + bump version"
run_gate "$dir"
assert_rc "kind renamed alongside version bump -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 4: Namespaced flipped, ModuleVersion unchanged -> FAIL. A scope
# change is a real documentation decision (pkg/kubernetes/README.md's own
# stated rule), not provenance churn.
dir="$(new_repo)"; base_fixture "$dir"
sed -i '0,/Namespaced: true/s//Namespaced: false/' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "flip Namespaced"
run_gate "$dir"
assert_rc "scope change with no version bump -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 5: a row added (line count changes) -> FAIL. The hunk-size guard
# (newcount == oldcount) must still block this; the provenance path never
# even gets a chance to run on an unbalanced hunk.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
EOF
sed -i '/Alertmanager/a\	{Group: "monitoring.coreos.com", Version: "v1", Kind: "PodMonitor", ModuleVersion: "v0.93.1", Namespaced: true},' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "add a row"
run_gate "$dir"
assert_rc "row added, no doc touch -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 6: the identical ModuleVersion-only edit, but the file carries no
# "Code generated ... DO NOT EDIT." header -> FAIL. is_generated_file() must
# still gate the provenance path exactly as it gates the marker path; a
# hand-written file cannot self-exempt by merely looking like a table.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
docs_map > "$dir/docs-map.yaml"
cat > "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// hand-written, not generated

package tables

var kinds = []KindInfo{
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus", ModuleVersion: "v0.93.1", Namespaced: true},
	{Group: "monitoring.coreos.com", Version: "v1", Kind: "Alertmanager", ModuleVersion: "v0.93.1", Namespaced: true},
}
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
sed -i 's/v0\.93\.1/v0.94.0/g' "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump version, no header"
run_gate "$dir"
assert_rc "version bump without generated-code header -> FAIL" "1" "$?"
rm -rf "$dir"

# Fixture 7: a pathological line carrying the recognized field name twice ->
# FAIL. mask_provenance_field()'s exactly-one-occurrence check must reject
# this rather than mask the first (or last) match and call it trivial.
dir="$(new_repo)"; base_fixture "$dir"
cat >> "$dir/pkg/tables/zz_generated_tables.go" <<'EOF'
// pathological: two ModuleVersion occurrences on one line
var _ = struct{ A, B string }{ModuleVersion: "v0.93.1", ModuleVersion: "v0.93.1"}
EOF
git -C "$dir" add -A && git -C "$dir" commit -q -m "add pathological line"
git -C "$dir" branch -qf base_marker HEAD
sed -i 's/ModuleVersion: "v0.93.1", ModuleVersion: "v0.93.1"/ModuleVersion: "v0.94.0", ModuleVersion: "v0.94.0"/' \
  "$dir/pkg/tables/zz_generated_tables.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump both occurrences"
run_gate "$dir"
assert_rc "field name appears twice on one line -> FAIL" "1" "$?"
rm -rf "$dir"

# --- Regression: pre-existing marker path must still work unchanged -----

# Fixture 8: marker-path package mapped — const bump WITH marker -> OK.
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
cat > "$dir/docs-map.yaml" <<'EOF'
repo_type: go-library
docs_only: false
code_roots: [pkg]
packages:
  - path: pkg/tables
    readme: pkg/tables/README.md
    guides: []
EOF
cat > "$dir/pkg/tables/gen.go" <<'EOF'
// Code generated by sync-versions.sh; DO NOT EDIT.

package tables

const GoVersion = "1.25.0" // doc-gate:trivial
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
sed -i 's/1\.25\.0/1.26.0/' "$dir/pkg/tables/gen.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump go version"
run_gate "$dir"
assert_rc "marked const value bump, no doc touch -> OK (regression)" "0" "$?"
rm -rf "$dir"

# Fixture 9: same file, value bumped WITHOUT the marker -> FAIL (regression).
dir="$(new_repo)"
mkdir -p "$dir/pkg/tables"
cat > "$dir/docs-map.yaml" <<'EOF'
repo_type: go-library
docs_only: false
code_roots: [pkg]
packages:
  - path: pkg/tables
    readme: pkg/tables/README.md
    guides: []
EOF
cat > "$dir/pkg/tables/gen.go" <<'EOF'
// Code generated by sync-versions.sh; DO NOT EDIT.

package tables

const GoVersion = "1.25.0"
EOF
echo "# tables" > "$dir/pkg/tables/README.md"
git -C "$dir" add -A && git -C "$dir" commit -q -m base
git -C "$dir" branch -q base_marker
sed -i 's/1\.25\.0/1.26.0/' "$dir/pkg/tables/gen.go"
git -C "$dir" add -A && git -C "$dir" commit -q -m "bump go version, no marker"
run_gate "$dir"
assert_rc "unmarked const value bump, no doc touch -> FAIL (regression)" "1" "$?"
rm -rf "$dir"

echo "passed: $pass_count, failed: $failures"
[ "$failures" -eq 0 ]
